package mask

import "github.com/wfusion/gofusion/common/utils"

const (
	ErrNotReach             utils.Error = "[mask] code should not reach here"
	ErrHasNotConfigured     utils.Error = "[mask] Engine has not been configed yet, call ApplyConfig* api"
	ErrConfEmpty            utils.Error = "[mask] configString is empty"
	ErrConfigUrlEmpty       utils.Error = "[mask] configURL is empty"
	ErrConfPathEmpty        utils.Error = "[mask] confPath is empty"
	ErrConfVerifyFailed     utils.Error = "[mask] config verify failed"
	ErrDisableRuleFailed    utils.Error = "[mask] rule is in DisableRules but not found in Rules"
	ErrAuthFailed           utils.Error = "[mask] Authentication Failed"
	ErrRemoteCfgFailed      utils.Error = "[mask] remote config failed, will load default config"
	ErrProcessAfterClose    utils.Error = "[mask] Engine has been closed"
	ErrNewEngineDebug       utils.Error = "[mask] NewEngineDebug is only used for debug, register your psm on DLP management system."
	ErrMaxInputLimit        utils.Error = "[mask] exceed max input limitation"
	ErrPositionError        utils.Error = "[mask] length of posistion parameter must be 2"
	ErrRegexNeedString      utils.Error = "[mask] Regex value should be string"
	ErrRegexCompileFailed   utils.Error = "[mask] Regex compile error"
	ErrDictNeedStringArray  utils.Error = "[mask] Dict rule needs string array"
	ErrReEmpty              utils.Error = "[mask] re object is nil"
	ErrMaskWorkerNotfound   utils.Error = "[mask] mask worker not found"
	ErrLoadMaskNameConflict utils.Error = "[mask] Load mask rule name conflict"
	ErrPanic                utils.Error = "[mask] Panic in mask"
	ErrMaskNotSupport       utils.Error = "[mask] Mask Method not support"
	ErrMaskFailed           utils.Error = "[mask] Mask Failed, input is returned"
	ErrMaskTagNotSupport    utils.Error = "[mask] Mask() dose not support with MaskType: Tag, which is used in Deiendity()"
	ErrMaskNameConflict     utils.Error = "[mask] MaskName conflicts with MaskRules.RuleName"
	ErrMaskRuleNotfound     utils.Error = "[mask] Mask rule is not Found"
	ErrDataMarshal          utils.Error = "[mask] data marshal error"
	ErrSendRequest          utils.Error = "[mask] sendRequest error"
	ErrMaskStructInput      utils.Error = "[mask] input of MaskStruct must be a pointer of a strcut"
	ErrMaskStructOutput     utils.Error = "[mask] Internal Error of MaskStruct, output is nil"
	ErrOnlyForLog           utils.Error = "[mask] NewLogProcessor() has been called. engine can be only used for log"
)
